

#GET ALL ITEM
GET http://localhost:8000/api/items/

### GET SINGLE ITEM
@itemId = 1
GET http://localhost:8000/api/items/{{itemId}}

### CREATE A DINO

POST http://localhost:8000/api/items/
Authorization: Bearer
Content-Type: application/json

{}

### register a user

POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "password": "theopass",
  "passwordConfirmation": "theopass",
  "username": "theo3",
  "email": "theo@email.com",
  "profileImage": "image.jpg"
}

### login a user

POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "theo@email.com",
  "password": "theopass"
}

### CREATE MISC COMMENT

POST http://localhost:8000/api/items/1/comments/
Content-Type: application/json

{
  "content": "Misc comment for one."
}
